AWSTemplateFormatVersion: '2010-09-09'
Description: A simple AWS CloudFormation template for a Lambda function and an API Gateway.

Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: arn:aws:iam::123456789012:role/lambda-role
      Code:
        S3Bucket: mybucket
        S3Key: mykey.zip
      Runtime: nodejs12.x

  MyApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: MyApiGateway
      Description: An API Gateway to invoke the Lambda function
      FailOnWarnings: true

  MyLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt MyLambdaFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':'
          - !Ref MyApiGateway
          - '/*/*'

Outputs:
  LambdaFunctionName:
    Description: "The name of the Lambda function"
    Value: !Ref MyLambdaFunction
  ApiGatewayInvokeURL:
    Description: "The URL to invoke the API Gateway"
    Value: !Sub "https://${MyApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod"
